var interfaceConfig = {
    CANVAS_EXTRA: 104,
    CANVAS_RADIUS: 7,
    SHADOW_COLOR: '#ffffff',
    INITIAL_TOOLBAR_TIMEOUT: 20000,
    TOOLBAR_TIMEOUT: 4000,
    DEFAULT_REMOTE_DISPLAY_NAME: "Videochat Yarner",
    DEFAULT_DOMINANT_SPEAKER_DISPLAY_NAME: "Speaker",
    DEFAULT_LOCAL_DISPLAY_NAME: "It's Me!",
    SHOW_JITSI_WATERMARK: true,
    JITSI_WATERMARK_LINK: "http://yarn-me.com",
    SHOW_BRAND_WATERMARK: false,
    BRAND_WATERMARK_LINK: "",
    SHOW_POWERED_BY: false,
    GENERATE_ROOMNAMES_ON_WELCOME_PAGE: true,
    APP_NAME: "Yarn Videochat",
    ACTIVE_SPEAKER_AVATAR_SIZE: 100
};
